### ISSUE TITLE
Anzeigen des Persönlichen Stundenplans und nicht nur der der Stufe

### ISSUE THREAD

**Issue by alessioC42** [lanis-mobile/lanis-mobile#247]
Es sollte eine recht überschaubare Aufgabe sein. Die DOM-ID in der timtable.dart müsste nach einer einstellung geändert werden und das ganze irgendwie noch mit in den Offline Speicher.

**Comment by PU-OL** [comment]
Wäre es auch möglich das der Stundenplan zwischen A und B Woche wechseln kann? Da wir zum Beispiel in der einen Woche das eine und in der anderen Woche ein anderes Fach haben.

**Comment by alessioC42** [comment]
A/B Wochen zu unterstützen klingt gut. Ich persönlich habe lediglich Zugang zu einem Account, der A/A Wochen hat. Um sowas zu implementieren müssten wir wissen, wie sixh das Schulportal bei A/B Wochen verhält. Und ob es Ausnahmen für weitere Dinge gibt.

**Comment by Rajala1404** [comment]
> Ich persönlich habe lediglich Zugang zu einem Account, der A/A Wochen hat.

Mein Account hat A/B Wochen kann aber nicht selbst zwischen den wechseln
