### ISSUE TITLE
Zeiten im Stundenplan

### ISSUE THREAD

**Issue by PU-OL** [lanis-mobile/lanis-mobile#256]
Der Stundenplan wir in der App immer mit einer Uhrzeit angezeigt, die jedoch je nach Schule teilweise falsch angezeigt wird, da es bei uns zum Beispiel für die Lehrer noch eine Frühschicht gibt. Dadurch sind bei uns zum Beispiel Stunden und Pausen um bis zu 45Minuten verschoben
<img width="285" alt="Screemshot_234567890" src="https://github.com/user-attachments/assets/449ee0c4-bd4d-40b6-b5ce-091b7657c5f7">
<img width="375" alt="Bildschirmfoto 2024-09-10 um 21 17 09 jpeg" src="https://github.com/user-attachments/assets/4f15a8c0-c2f4-404a-ab2b-140fc816ecae">

**Comment by alessioC42** [comment]
Könntest du im Browser CTRL+I drücken und den code dann hier Hochladen (persönliche infos, wie namen etc solltest du streichen, wenn dir das wichtig ist). Dann kann ich direkt damit testen. Wenn du das nicht public machen willst kannst du mir auch ne mail mit dem dokument an alessioc42.dev@gmail.com senden.
