### ISSUE TITLE
The proxy is not working on iOS devices when configured automatically.

### ISSUE THREAD

**Issue by Rajala1404** [lanis-mobile/lanis-mobile#265]
The current implementation of the Proxy only works if the Proxy is set to Manual in the iOS settings. If the Proxy is configured as Automatic in the Settings, it returns NULL. Need to Update the http_proxy dependency for this.

**Comment by pinpolhoxx** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme
I put the necessary dlls in the archive

**Comment by alessioC42** [comment]
In that case I would suggest moving the http_proxy fork to the GitHub organisation to organize our changes and give every member access.
