### ISSUE TITLE
Stundenplan lädt nicht

### ISSUE THREAD

**Issue by TheBest6337** [lanis-mobile/lanis-mobile#280]
Ich habe mir vor ein paar Tagen diese wundervolle App runtergeladen, nur leider funktioniert bei mir auf dem Handy(Nothing Phone 2) als auch auf dem Tablet(Ipad Air 2024) bei dem Stundenplan nichts außer das eine Lade Animation angezeigt wird.

**Comment by TheBest6337** [comment]
![IMG_0145](https://github.com/user-attachments/assets/e965104d-fa54-4e10-b26e-528e21c86717)

**Comment by Rajala1404** [comment]
Versuch mal den Button mit den Personen zu klicken und laden andere tabs wie mein Unttericht auch nicht?

**Comment by alessioC42** [comment]
> Versuch mal den Button mit den Personen zu klicken und laden andere tabs wie mein Unttericht auch nicht?

Sollte keinen unterschied machen. Die Pläne werden gleichzeitig geparst.

**Comment by Rajala1404** [comment]
Ich dachte vielleicht hat das was mit dem Persönlichen Stundenplan zu tun.
Könnte es sein deine Schuhle keinen Persönlichen Stundeplan hat? Und laden andere tabs auch nicht?

**Comment by TheBest6337** [comment]
> Versuch mal den Button mit den Personen zu klicken und laden andere tabs wie mein Unttericht auch nicht?

Macht keinen Unterschied und wir haben eigentlich einen persönlichen Stundenplan

**Comment by Rajala1404** [comment]
Komisch laden den andere Tabs und wenn nein bist du in deinem Schul Netzwer und wenn ja hat es ne Proxy?

**Comment by alessioC42** [comment]
Daran wird es nicht liegen. Es wird ein parsing Problem sein. Ich habe da letztens was angepasst. 

@TheBest6337 Kannst du Mir über discord oder E-Mail das HTML Dokument für die Lanis-Website von dem stundenplan zusenden. Dann kann ich Mir das Mal genauer anschauen.

**Comment by TheBest6337** [comment]
@alessioC42 ja mach ich nach der Schule

**Comment by alessioC42** [comment]
Ich glaube, ich habe das Problem gefunden: Die Schule (5202) hat ein Feld für den Samstagsunterricht. Das führt zu Fehlern beim Interieren wegen dem Tabellenindex.
