### ISSUE TITLE
iOS dark mode icon

### ISSUE THREAD

**Issue by alessioC42** [lanis-mobile/lanis-mobile#286]
Maybe iconkitchen supports this now?

**Comment by alessioC42** [comment]
![IMG_2031.png](https://github.com/user-attachments/assets/91cb550d-6d74-4eb7-8309-2f118c3302f1)

**Comment by Rajala1404** [comment]
On my device (iOS 18.0.1 Developer Beta) that worked and lanis supported theming

**Comment by Rajala1404** [comment]
iOS Themed icons are supported on iOS 18.1 and higher so this issue is no longer needed.
