### ISSUE TITLE
Use native_dio_adapter

### ISSUE THREAD

**Issue by kurwjan** [lanis-mobile/lanis-mobile#312]
Currently we use the [default adapter written in dart](https://pub.dev/documentation/dio/latest/dio/HttpClientAdapter-class.html),
but we can also use the [native dio adapter](https://github.com/cfug/dio/tree/main/plugins/native_dio_adapter) which uses the [Foundation URL Loading System](https://developer.apple.com/documentation/foundation/url_loading_system) on iOS and [Cronet](https://developer.android.com/develop/connectivity/cronet) (Chromium-based network stack) on Android.

On iOS it uses the [proxy without doing some nasty native platform stuff](https://pub.dev/packages/cupertino_http#motivation). It could be also (a tiny bit) faster because it uses native APIs and they support HTTP/2 which some endpoints on Lanis support.

Only "disadvantage" is, that it [requires the Google Play Services](https://pub.dev/documentation/cronet_http/latest/#use-embedded-cronet) on Android.

**Comment by Rajala1404** [comment]
If it requires GMS I wouldn't implement it. For example Huawei devices wouldn't work and  maybe even MicroG wouldn't work

**Comment by kurwjan** [comment]
> If it requires GMS I wouldn't implement it. For example Huawei devices wouldn't work and  maybe even MicroG wouldn't work

It only requires Google Play Services so [MicroG supports it](https://github.com/microg/cronet-build).
