### ISSUE TITLE
Redesign settings

### ISSUE THREAD

**Issue by kurwjan** [lanis-mobile/lanis-mobile#322]
Idk, hab gerade bock darauf; macht spaß mit Figma zu experimentieren

hab auch schon einen Mockup,
hab als Inspiration die Android 15 Settings App genommen und diverse andere Android (Google) System Apps.
Anscheined soll bei Material 3 die Farbe `Surface` nicht mehr wirklich benutzt werden und wurde durch 7 Farben oder so ersetzt:
+ Alle Surface Containers (Lowest to Highest)
+ Surface Dim
+ Surface Bright

Die Themes Page ist aktuell auch grässlich

Außerdem will ich auf Flutter 3.27 updaten und Predictive Back aktivieren.

<img width="200" src="https://github.com/user-attachments/assets/afe07cf5-358b-4e02-a772-d42cadd8441b" />
<img width="200" src="https://github.com/user-attachments/assets/77b5a1f5-d14f-4a5e-9d56-14126b835833" />
<img width="200" src="https://github.com/user-attachments/assets/d7cad622-25bf-4293-a191-4e3199ce581b" />
<img width="200" src="https://github.com/user-attachments/assets/5c6869d6-d177-4055-b99c-1b86a4c80ec7" />
<img width="200" src="https://github.com/user-attachments/assets/9cf6dea3-cc1f-44fc-8b33-d6e57d2ff0be" />
<img width="200" src="https://github.com/user-attachments/assets/8da19096-5c8a-4dc5-84d2-63aeedcf7ed8" />
<img width="200" src="https://github.com/user-attachments/assets/39bf1ce8-7280-497e-b425-ac2046b2b1f6" />
<img width="200" src="https://github.com/user-attachments/assets/9bd99dd8-4024-43ec-8de3-f53709c62bb1" />

**Comment by alessioC42** [comment]
Sehr geil!

**Comment by TheBest6337** [comment]
Sieht echt clean aus
